// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiMFRbUdiuXpzaI9LqI_OXSxVkL_xjVjI',
    appId: '1:517727122575:web:d446acfc23b687817a6cfa',
    messagingSenderId: '517727122575',
    projectId: 'flowerio-app',
    authDomain: 'flowerio-app.firebaseapp.com',
    storageBucket: 'flowerio-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLPUM__kag6geUXnwQhj_k_tBhMLE9KDw',
    appId: '1:517727122575:android:88eb0fd14e69923c7a6cfa',
    messagingSenderId: '517727122575',
    projectId: 'flowerio-app',
    storageBucket: 'flowerio-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh8AETnN0bsNlaZ-QFWEvUtSNPh71ziqE',
    appId: '1:517727122575:ios:f0d228b0c43cec4a7a6cfa',
    messagingSenderId: '517727122575',
    projectId: 'flowerio-app',
    storageBucket: 'flowerio-app.appspot.com',
    iosClientId: '517727122575-ud8p8j178b6pt6183me3m91k42gb6843.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh8AETnN0bsNlaZ-QFWEvUtSNPh71ziqE',
    appId: '1:517727122575:ios:f0d228b0c43cec4a7a6cfa',
    messagingSenderId: '517727122575',
    projectId: 'flowerio-app',
    storageBucket: 'flowerio-app.appspot.com',
    iosClientId: '517727122575-ud8p8j178b6pt6183me3m91k42gb6843.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerioApp',
  );
}
